package com.example.sweater.domain;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Entity;

@Entity //Если Энтити - дб конструктор без параметров!!!!!!!!!!!!!
public class Message {
    @Id //Talk that it is ID
    @GeneratedValue(strategy = GenerationType.AUTO) //Talk that it must be autogenerated
    private Integer id;

    private String text;
    private String tag;

    public Message() {
        //Пустой конструктор, иначе Спринг и прочие фреймворки не согут создать данный класс
    }

    public Message(String text, String tag) {
        this.text = text;
        this.tag = tag;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getText() {
        return text;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }
}
